name: Run Autotests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autotests/requirements.txt
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Установка Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo rm -f google-chrome-stable_current_amd64.deb
          
          # Установка ChromeDriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=${CHROME_VERSION%.*.*}
          wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}
          CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_${CHROME_MAJOR_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Verify installations
        run: |
          google-chrome --version
          chromedriver --version
          
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          pytest autotests/tests/ -v --alluredir=allure-results
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: allure-results
