name: Run Autotests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r autotests/requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          export PATH=$PATH:/usr/bin/chromium-browser
          pytest autotests/tests/ -v --alluredir=allure-results
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: allure-results
